version: "3"

services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_short_url
    ports:
      - "5432:5432"

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_USERNAME=admin
      - REDIS_PASSWORD=admin
    ports:
      - "6379:6379"
